import { DnsRecord, FirewallRule, IpAccessRule, PageRule } from '@/types/cloudflare';

export interface TerraformExportOptions {
  includeDns?: boolean;
  includeWaf?: boolean;
  includeSsl?: boolean;
  includePageRules?: boolean;
  includeZoneSettings?: boolean;
}

export function sanitizeTerraformId(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_{2,}/g, '_') || 'resource';
}

export function generateTerraformCode(
  zone: { id: string; name: string },
  dnsRecords: DnsRecord[] = [],
  firewallRules: FirewallRule[] = [],
  ipRules: IpAccessRule[] = [],
  sslData: any = null,
  pageRules: PageRule[] = [],
  options: TerraformExportOptions = {
    includeDns: true,
    includeWaf: true,
    includeSsl: true,
    includePageRules: true,
    includeZoneSettings: true,
  }
): { mainTf: string; tfvars: string } {
  const zoneResourceName = sanitizeTerraformId(zone.name);
  const sections: string[] = [];

  // Header and Provider Requirements
  sections.push(`# ------------------------------------------------------------------------------
# Cloudflare Infrastructure as Code (IaC)
# Generated by Cloudflare DevSecOps Manager
# Zone: ${zone.name} (${zone.id})
# Exported on: ${new Date().toISOString()}
# ------------------------------------------------------------------------------

terraform {
  required_version = ">= 1.3.0"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.25.0"
    }
  }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# ------------------------------------------------------------------------------
# Input Variables
# ------------------------------------------------------------------------------
variable "cloudflare_api_token" {
  type        = string
  description = "Cloudflare API Token with Edit permissions for Zone: ${zone.name}"
  sensitive   = true
}

variable "zone_id" {
  type        = string
  description = "Cloudflare Zone ID for ${zone.name}"
  default     = "${zone.id}"
}
`);

  // Zone Settings Override
  if (options.includeZoneSettings || options.includeSsl) {
    const sslMode = sslData?.ssl_mode || 'strict';
    const minTls = sslData?.min_tls_version || '1.2';
    const alwaysHttps = sslData?.always_use_https ? 'on' : 'off';
    const autoHttps = sslData?.automatic_https_rewrites ? 'on' : 'off';

    sections.push(`# ------------------------------------------------------------------------------
# Zone Settings & SSL/TLS Security Posture
# ------------------------------------------------------------------------------
resource "cloudflare_zone_settings_override" "${zoneResourceName}_settings" {
  zone_id = var.zone_id

  settings {
    ssl                      = "${sslMode}"
    min_tls_version          = "${minTls}"
    always_use_https         = "${alwaysHttps}"
    automatic_https_rewrites = "${autoHttps}"
    brotli                   = "on"
    http3                    = "on"
    0rtt                     = "on"
    security_level           = "medium"
    browser_check            = "on"
    challenge_ttl            = 1800
  }
}
`);
  }

  // DNS Records
  if (options.includeDns && dnsRecords.length > 0) {
    sections.push(`# ------------------------------------------------------------------------------
# DNS Records Configuration (${dnsRecords.length} records)
# ------------------------------------------------------------------------------`);

    dnsRecords.forEach((rec, idx) => {
      const recNameFormatted = rec.name.replace(`.${zone.name}`, '') === zone.name ? '@' : rec.name.replace(`.${zone.name}`, '');
      const resourceId = sanitizeTerraformId(`${rec.type}_${recNameFormatted}_${idx}`);
      const ttlVal = rec.ttl === 1 ? 1 : rec.ttl;
      const commentBlock = rec.comment ? `\n  comment = ${JSON.stringify(rec.comment)}` : '';
      const priorityBlock = rec.type === 'MX' && rec.priority ? `\n  priority = ${rec.priority}` : '';

      sections.push(`resource "cloudflare_record" "${resourceId}" {
  zone_id = var.zone_id
  name    = "${recNameFormatted}"
  type    = "${rec.type}"
  content = ${JSON.stringify(rec.content)}
  proxied = ${rec.proxied}${priorityBlock}${commentBlock}
  ttl     = ${ttlVal}
}
`);
    });
  }

  // WAF Firewall Rules & Filters
  if (options.includeWaf && firewallRules.length > 0) {
    sections.push(`# ------------------------------------------------------------------------------
# WAF Firewall Rules (${firewallRules.length} rules)
# ------------------------------------------------------------------------------`);

    firewallRules.forEach((rule, idx) => {
      const filterResId = sanitizeTerraformId(`filter_${rule.description || idx}`);
      const ruleResId = sanitizeTerraformId(`waf_${rule.description || idx}`);
      const expr = rule.filter?.expression || 'true';

      sections.push(`resource "cloudflare_filter" "${filterResId}" {
  zone_id     = var.zone_id
  description = ${JSON.stringify(rule.description || `Filter #${idx + 1}`)}
  expression  = ${JSON.stringify(expr)}
}

resource "cloudflare_firewall_rule" "${ruleResId}" {
  zone_id     = var.zone_id
  description = ${JSON.stringify(rule.description || `WAF Rule #${idx + 1}`)}
  filter_id   = cloudflare_filter.${filterResId}.id
  action      = "${rule.action}"
  paused      = ${Boolean(rule.paused)}
  priority    = ${rule.priority || idx + 1}
}
`);
    });
  }

  // IP Access Rules
  if (options.includeWaf && ipRules.length > 0) {
    sections.push(`# ------------------------------------------------------------------------------
# IP Access Rules (${ipRules.length} rules)
# ------------------------------------------------------------------------------`);

    ipRules.forEach((ipRule, idx) => {
      const resId = sanitizeTerraformId(`ip_${ipRule.configuration?.target}_${ipRule.configuration?.value}_${idx}`);
      const notesBlock = ipRule.notes ? `\n  notes   = ${JSON.stringify(ipRule.notes)}` : '';

      sections.push(`resource "cloudflare_ip_list" "${resId}" {
  # Alternative native access rule
  zone_id = var.zone_id
  mode    = "${ipRule.mode}"
  configuration = {
    target = "${ipRule.configuration?.target}"
    value  = "${ipRule.configuration?.value}"
  }${notesBlock}
}
`);
    });
  }

  // Page Rules
  if (options.includePageRules && pageRules.length > 0) {
    sections.push(`# ------------------------------------------------------------------------------
# Page Rules Configuration (${pageRules.length} rules)
# ------------------------------------------------------------------------------`);

    pageRules.forEach((pr, idx) => {
      const resId = sanitizeTerraformId(`pagerule_${idx}_${pr.targets?.[0]?.constraint?.value || 'target'}`);
      const targetUrl = pr.targets?.[0]?.constraint?.value || `*${zone.name}/*`;
      const actionsBlocks: string[] = [];

      pr.actions?.forEach(act => {
        if (act.id === 'forwarding_url') {
          actionsBlocks.push(`    forwarding_url {
      url         = "${act.value?.url || ''}"
      status_code = ${act.value?.status_code || 301}
    }`);
        } else if (act.id === 'always_use_https') {
          actionsBlocks.push(`    always_use_https = true`);
        } else if (act.id === 'cache_level') {
          actionsBlocks.push(`    cache_level = "${act.value}"`);
        } else if (act.id === 'security_level') {
          actionsBlocks.push(`    security_level = "${act.value}"`);
        }
      });

      sections.push(`resource "cloudflare_page_rule" "${resId}" {
  zone_id  = var.zone_id
  target   = "${targetUrl}"
  priority = ${pr.priority || idx + 1}
  status   = "active"

  actions {
${actionsBlocks.join('\n')}
  }
}
`);
    });
  }

  // Outputs
  sections.push(`# ------------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------------
output "zone_id" {
  description = "Target Zone ID"
  value       = var.zone_id
}

output "zone_name" {
  description = "Target Zone Name"
  value       = "${zone.name}"
}
`);

  const mainTf = sections.join('\n');

  const tfvars = `# ------------------------------------------------------------------------------
# Terraform Variables for ${zone.name}
# ------------------------------------------------------------------------------
cloudflare_api_token = "YOUR_CLOUDFLARE_API_TOKEN_HERE"
zone_id              = "${zone.id}"
`;

  return { mainTf, tfvars };
}
